<?php
/**
 * Smoke tests: the plugin loads under WordPress and its version metadata agrees.
 *
 * Generated by wordpress-plugin-boilerplate/tooling. Add plugin-specific tests
 * alongside this file as tests/test-*.php (or tests/**/*Test.php).
 */

class Test_Plugin_Load extends WP_UnitTestCase {

	const PLUGIN_FILE = '__PLUGIN_DIR__/__MAIN_FILE__';

	public function test_plugin_file_is_loaded() {
		$this->assertContains( WP_PLUGIN_DIR . '/' . self::PLUGIN_FILE, get_included_files() );
	}

	public function test_header_version_matches_readme_stable_tag() {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$header = get_plugin_data( WP_PLUGIN_DIR . '/' . self::PLUGIN_FILE, false, false );
		$readme = file_get_contents( WP_PLUGIN_DIR . '/' . dirname( self::PLUGIN_FILE ) . '/readme.txt' );

		$this->assertNotEmpty( $header['Version'], 'Plugin header has a Version' );
		$this->assertSame( 1, preg_match( '/^Stable tag:\s*(\S+)/m', $readme, $m ), 'readme.txt has a Stable tag' );
		$this->assertSame( $header['Version'], $m[1], 'Header version matches readme Stable tag' );
	}

	public function test_wordpress_is_installed() {
		$this->assertTrue( is_blog_installed() );
		$this->assertGreaterThan( 0, did_action( 'init' ) );
	}
}
