<?php
/**
 * GitHub release updater.
 *
 * Generated by wordpress-plugin-boilerplate/tooling for GitHub-only plugins (no `Type:`
 * header in readme.txt) - fix there first, then run bin/sync-tooling.sh.
 */

use __UPDATER_NS__\GitHub_Updater;

class Test_GitHub_Updater extends WP_UnitTestCase {

	const PLUGIN = '__PLUGIN_DIR__/__MAIN_FILE__';
	const REPO   = 'acme/example-repo';

	/**
	 * Requests seen by the HTTP mock.
	 *
	 * @var array[]
	 */
	private $requests = array();

	/**
	 * Location header the fake /releases/latest answers with, or a WP_Error.
	 *
	 * @var string|WP_Error
	 */
	private $location = '';

	public function set_up() {
		parent::set_up();
		$this->requests = array();
		add_filter( 'pre_http_request', array( $this, 'fake_http' ), 10, 3 );
		delete_site_transient( $this->updater()->cache_key() );
		delete_site_transient( 'update_plugins' );
	}

	public function tear_down() {
		remove_filter( 'pre_http_request', array( $this, 'fake_http' ), 10 );
		parent::tear_down();
	}

	public function fake_http( $pre, $args, $url ) {
		$this->requests[] = array( 'url' => $url, 'args' => $args );
		if ( false !== strpos( $url, 'api.wordpress.org/plugins/update-check' ) ) {
			// Core gives up on the whole check (before any Update URI filter) if this fails.
			return array(
				'headers'  => array(),
				'body'     => wp_json_encode( array( 'plugins' => array(), 'translations' => array(), 'no_update' => array() ) ),
				'response' => array( 'code' => 200, 'message' => 'OK' ),
				'cookies'  => array(),
				'filename' => null,
			);
		}
		if ( false === strpos( $url, 'https://github.com/' ) ) {
			return new WP_Error( 'blocked', 'Only GitHub and the WordPress.org update check are faked in tests' );
		}
		if ( is_wp_error( $this->location ) ) {
			return $this->location;
		}
		return array(
			'headers'  => array( 'location' => $this->location ),
			'body'     => '',
			'response' => array( 'code' => 302, 'message' => 'Found' ),
			'cookies'  => array(),
			'filename' => null,
		);
	}

	private function updater() {
		return new GitHub_Updater( WP_PLUGIN_DIR . '/' . self::PLUGIN );
	}

	private function github_requests() {
		return array_values( array_filter( $this->requests, function ( $r ) {
			return 0 === strpos( $r['url'], 'https://github.com/' );
		} ) );
	}

	private function plugin_data( $uri = 'https://github.com/' . self::REPO ) {
		return array( 'UpdateURI' => $uri, 'Version' => '1.0.0' );
	}

	public function test_main_file_declares_github_update_uri() {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$data = get_plugin_data( WP_PLUGIN_DIR . '/' . self::PLUGIN, false, false );
		$this->assertNotSame( '', GitHub_Updater::repo_from_uri( $data['UpdateURI'] ), 'Update URI header must be https://github.com/<owner>/<repo>' );
	}

	public function test_updater_is_hooked() {
		$this->assertTrue( has_filter( 'update_plugins_github.com' ) );
	}

	public function test_latest_release_from_redirect() {
		$this->location = 'https://github.com/' . self::REPO . '/releases/tag/v2.3.4';

		$update = $this->updater()->check( false, $this->plugin_data(), self::PLUGIN );

		$this->assertSame( '2.3.4', $update['version'] );
		$this->assertSame( '__PLUGIN_DIR__', $update['slug'] );
		$this->assertSame( 'https://github.com/' . self::REPO . '/releases/download/v2.3.4/__PLUGIN_DIR__-2.3.4.zip', $update['package'] );
		$request = $this->github_requests()[0];
		$this->assertSame( 'https://github.com/' . self::REPO . '/releases/latest', $request['url'] );
		$this->assertSame( 'HEAD', $request['args']['method'] );
		$this->assertSame( 0, $request['args']['redirection'] );
		$this->assertLessThanOrEqual( 5, $request['args']['timeout'] );
	}

	public function test_lookup_is_cached() {
		$this->location = 'https://github.com/' . self::REPO . '/releases/tag/2.3.4';
		$updater        = $this->updater();

		$updater->check( false, $this->plugin_data(), self::PLUGIN );
		$update = $updater->check( false, $this->plugin_data(), self::PLUGIN );

		$this->assertSame( '2.3.4', $update['version'], 'Tags without a v prefix work too' );
		$this->assertCount( 1, $this->github_requests() );
	}

	public function test_unreachable_github_is_quiet_and_cached() {
		$this->location = new WP_Error( 'http_request_failed', 'cURL error 28: Connection timed out' );
		$updater        = $this->updater();

		$this->assertFalse( $updater->check( false, $this->plugin_data(), self::PLUGIN ) );
		$this->assertFalse( $updater->check( false, $this->plugin_data(), self::PLUGIN ) );
		$this->assertCount( 1, $this->github_requests(), 'A failure is cached so an outage does not slow every check' );
	}

	/**
	 * @dataProvider not_a_release_provider
	 */
	public function test_no_update_without_a_release_tag( $location ) {
		$this->location = $location;

		$this->assertFalse( $this->updater()->check( false, $this->plugin_data(), self::PLUGIN ) );
	}

	public function not_a_release_provider() {
		return array(
			'no releases yet' => array( '' ),
			'pre-release tag' => array( 'https://github.com/acme/example-repo/releases/tag/v2.0.0-beta.1' ),
			'not a tag'       => array( 'https://github.com/acme/example-repo/releases' ),
		);
	}

	public function test_other_plugins_and_non_github_uris_are_ignored() {
		$this->location = 'https://github.com/' . self::REPO . '/releases/tag/v9.9.9';
		$updater        = $this->updater();

		$this->assertFalse( $updater->check( false, $this->plugin_data(), 'other/other.php' ) );
		$this->assertFalse( $updater->check( false, $this->plugin_data( 'https://example.com/acme/repo' ), self::PLUGIN ) );
		$this->assertSame( array( 'x' ), $updater->check( array( 'x' ), $this->plugin_data(), self::PLUGIN ), 'An earlier answer is kept' );
		$this->assertCount( 0, $this->github_requests() );
	}

	/**
	 * @dataProvider uri_provider
	 */
	public function test_repo_from_uri( $uri, $repo ) {
		$this->assertSame( $repo, GitHub_Updater::repo_from_uri( $uri ) );
	}

	public function uri_provider() {
		return array(
			array( 'https://github.com/acme/repo', 'acme/repo' ),
			array( 'https://github.com/acme/repo/', 'acme/repo' ),
			array( 'https://github.com/acme/my.repo-name.git', 'acme/my.repo-name' ),
			array( 'http://github.com/acme/repo', '' ),
			array( 'https://github.com/acme', '' ),
			array( 'https://github.com/acme/repo/releases', '' ),
			array( 'my-plugin', '' ),
			array( '', '' ),
		);
	}

	public function test_core_update_check_offers_the_release() {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$data           = get_plugin_data( WP_PLUGIN_DIR . '/' . self::PLUGIN, false, false );
		$repo           = GitHub_Updater::repo_from_uri( $data['UpdateURI'] );
		$this->location = 'https://github.com/' . $repo . '/releases/tag/v999.0.0';

		wp_update_plugins();

		$response = get_site_transient( 'update_plugins' )->response;
		$this->assertArrayHasKey( self::PLUGIN, $response );
		$this->assertSame( '999.0.0', $response[ self::PLUGIN ]->new_version );
		$this->assertStringEndsWith( '/releases/download/v999.0.0/__PLUGIN_DIR__-999.0.0.zip', $response[ self::PLUGIN ]->package );
	}

	public function test_view_details() {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
		$data = get_plugin_data( WP_PLUGIN_DIR . '/' . self::PLUGIN, false, false );
		$this->location = 'https://github.com/' . GitHub_Updater::repo_from_uri( $data['UpdateURI'] ) . '/releases/tag/v2.3.4';

		$info = $this->updater()->info( false, 'plugin_information', (object) array( 'slug' => '__PLUGIN_DIR__' ) );

		$this->assertSame( '2.3.4', $info->version );
		$this->assertStringContainsString( '/releases/tag/v2.3.4', $info->sections['changelog'] );
		$this->assertFalse( $this->updater()->info( false, 'plugin_information', (object) array( 'slug' => 'other' ) ) );
	}

	public function test_update_lands_in_the_installed_folder() {
		global $wp_filesystem;
		require_once ABSPATH . 'wp-admin/includes/file.php';
		WP_Filesystem();
		$remote = get_temp_dir() . 'fwupd-' . wp_generate_password( 6, false );
		wp_mkdir_p( $remote . '/__PLUGIN_DIR__' );
		file_put_contents( $remote . '/__PLUGIN_DIR__/__MAIN_FILE__', '<?php' );

		// Installed under a different folder name, e.g. from a GitHub source zip.
		$updater = new GitHub_Updater( WP_PLUGIN_DIR . '/__PLUGIN_DIR__-main/__MAIN_FILE__' );
		$source  = $updater->keep_folder( $remote . '/__PLUGIN_DIR__/', $remote, null, array( 'plugin' => '__PLUGIN_DIR__-main/__MAIN_FILE__' ) );

		$this->assertSame( $remote . '/__PLUGIN_DIR__-main/', $source );
		$this->assertFileExists( $remote . '/__PLUGIN_DIR__-main/__MAIN_FILE__' );
		$this->assertSame( $remote . '/x/', $updater->keep_folder( $remote . '/x/', $remote, null, array( 'plugin' => 'other/other.php' ) ) );
		$wp_filesystem->delete( $remote, true );
	}
}
